"""New / edit report screen: patient details, panel selection, editable results grid."""
import os
from datetime import datetime

from PySide6.QtCore import QDate, QDateTime, Qt, Signal
from PySide6.QtGui import QBrush, QColor, QFont
from PySide6.QtWidgets import (
    QAbstractItemView, QCheckBox, QComboBox, QDateEdit, QDateTimeEdit,
    QFileDialog, QFormLayout, QFrame,
    QGridLayout, QHBoxLayout, QHeaderView, QLabel, QLineEdit, QMessageBox,
    QPushButton, QScrollArea, QTableWidget, QTableWidgetItem, QVBoxLayout,
    QWidget,
)

from .. import billing, printing, storage
from .drive_prompt import apply_answer, ask_for_drive
from . import icons
from .theme import ACCENT, ACCENT_DARK, DANGER, MUTED, S2, S3, SURFACE_ALT
from . import theme as T
from .widgets import AmountDelegate, Card, PageHeader, hrule, icon_button
from ..models import BillItem, Billing, Report, TestRow
from ..panels import flag_for
from .. import templates
from ..report_html import build
from ..bill_html import build as build_bill
from ..util import safe_filename
from .. import validators as V

COLS = ["Test", "Result", "Unit", "Reference Range"]
BILL_COLS = ["Service / Test", f"Amount ({billing.CURRENCY})"]
DATE_FMT = "%d-%m-%Y %I:%M %p"
QT_DATE_FMT = "dd-MM-yyyy hh:mm AP"

# (stored code, what the operator sees). The code is what goes into the report
# file, so spelling the words out here changes only the display.
AGE_UNITS = [("Y", "Years"), ("M", "Months"), ("D", "Days")]

HEADING_ROLE = Qt.UserRole + 1

# One line of plain English per field, shown under it.
FIELD_HELP = {
    "name": "Full name of the patient, as it should appear on the report.",
    "age": "The patient's age, in the unit chosen beside it.",
    "patient_id": "Unique key generated by the app. Reused for repeat visits.",
    "phone": "Patient's number, ten digits. Printed on the bill. Optional.",
    "doctor": "Doctor who requested the test. Leave blank for a walk-in.",
    "sample": "What was collected - blood, serum, plasma or urine.",
    "collected": "When the sample was taken from the patient.",
    "reported": "When the result was finalised. Printed as the report date.",
    "remarks": "Optional note printed under the results, e.g. 'Repeat in 2 weeks'.",
    "bill_no": "Reference for this bill. Generated for you - overwrite it if the "
               "lab uses its own numbering.",
    "bill_date": "When the bill is raised. Printed on the bill.",
    "bill_type": "Cash, credit or insurance. Prints as the bill's heading.",
    "billed_by": "Who raised the bill. Prints as Printed By and Billed By.",
    "deposit": "How much the patient has already paid. Leave blank if nothing "
               "has been paid yet.",
}


class ReportForm(QWidget):
    saved = Signal()
    notify = Signal(str, str)   # (message, kind)

    # The bill's amount boxes open on a single click. Typing a bill is a run of
    # short numeric edits, and needing a double-click for each one is both slow
    # and the reason the column read as if it could not be typed into at all.
    BILL_TRIGGERS = (QAbstractItemView.CurrentChanged
                     | QAbstractItemView.DoubleClicked
                     | QAbstractItemView.SelectedClicked
                     | QAbstractItemView.EditKeyPressed
                     | QAbstractItemView.AnyKeyPressed)

    def __init__(self):
        super().__init__()
        self.current_id = ""
        self.current_report_no = ""
        self.current_created_at = ""
        self._loading = False
        self._styling = False
        self._bill_loading = False
        self.read_only = False

        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(S3)

        self.header = PageHeader("New Report", "Enter the patient's details and results")
        layout.addWidget(self.header)

        self.lock_bar = self._build_lock_bar()
        self.lock_bar.hide()
        layout.addWidget(self.lock_bar)

        # The cards live in a scroll area, and the action bar is pinned below
        # it. Laying them out directly would mean that on a short window the
        # page needs more height than it has, and Qt resolves that by squeezing
        # the stretchy card below its minimum - which makes the results grid
        # paint over its own buttons. Scrolling is the honest answer.
        content = QWidget()
        content.setObjectName("Bare")
        column = QVBoxLayout(content)
        column.setContentsMargins(0, 0, S2, 0)   # room for the scrollbar
        column.setSpacing(S3)
        column.addWidget(self._build_patient_box())
        column.addWidget(self._build_panel_box())
        column.addWidget(self._build_table_box(), 1)
        # Billing sits last, mirroring the printout: results first, then what
        # they cost. It reads down the page in the same order either way.
        column.addWidget(self._build_bill_box())

        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        scroll.setWidget(content)
        scroll.setFrameShape(QScrollArea.NoFrame)

        layout.addWidget(scroll, 1)
        layout.addLayout(self._build_actions())

        self.new_report()

    def set_lab_name(self, name: str):
        self.header.set_subtitle(
            f"{name} - enter the patient's details and results" if name
            else "Enter the patient's details and results")

    # ---------------------------------------------------------------- widgets
    @staticmethod
    def _described(widget, help_key: str, trailing: str = "") -> QWidget:
        """A field with its one-line description underneath.

        The description sits under the control rather than in a tooltip so it
        is readable without hunting for it - this app is used by staff who may
        never have been trained on it."""
        wrapper = QWidget()
        wrapper.setObjectName("Bare")
        column = QVBoxLayout(wrapper)
        column.setContentsMargins(0, 0, 0, 0)
        column.setSpacing(1)

        if trailing:
            top = QHBoxLayout()
            top.setContentsMargins(0, 0, 0, 0)
            top.setSpacing(S2)
            if isinstance(widget, QWidget):
                top.addWidget(widget)
            else:
                top.addLayout(widget)
            note = QLabel(trailing)
            note.setObjectName("Hint")
            top.addWidget(note)
            top.addStretch(1)
            column.addLayout(top)
        elif isinstance(widget, QWidget):
            column.addWidget(widget)
        else:
            column.addLayout(widget)

        description = QLabel(FIELD_HELP.get(help_key, ""))
        description.setObjectName("FieldHelp")
        description.setWordWrap(True)
        column.addWidget(description)
        return wrapper

    def _build_lock_bar(self) -> QFrame:
        bar = QFrame()
        bar.setObjectName("LockBar")
        row = QHBoxLayout(bar)
        row.setContentsMargins(S3, S2, S3, S2)
        row.setSpacing(S2 + 2)

        glyph = QLabel()
        glyph.setPixmap(icons.pixmap("lock", "#a15c07", 18))
        row.addWidget(glyph)

        self.lock_message = QLabel("")
        self.lock_message.setObjectName("LockText")
        self.lock_message.setWordWrap(True)
        row.addWidget(self.lock_message, 1)

        self.unlock_button = icon_button(
            "unlock", "Unlock to Edit",
            "Enter the edit password to change this report")
        self.unlock_button.clicked.connect(self.request_edit_access)
        row.addWidget(self.unlock_button)
        return bar

    @staticmethod
    def _set_date(field: QDateTimeEdit, text: str):
        """Put a stored date string back into a picker.

        Reports saved before the pickers existed hold whatever was typed, so an
        unreadable value falls back to now rather than throwing."""
        parsed = QDateTime.fromString(text or "", QT_DATE_FMT)
        if not parsed.isValid():
            parsed = QDateTime.fromString(text or "", "dd-MM-yyyy hh:mm AP")
        field.setDateTime(parsed if parsed.isValid() else QDateTime.currentDateTime())

    @staticmethod
    def _date_field() -> QDateTimeEdit:
        field = QDateTimeEdit()
        field.setDisplayFormat("dd-MM-yyyy  hh:mm AP")
        field.setCalendarPopup(True)
        field.setDateTime(QDateTime.currentDateTime())
        field.setMinimumDate(QDate(1900, 1, 1))
        field.setMaximumDateTime(QDateTime.currentDateTime().addYears(1))
        return field

    @staticmethod
    def _label(text: str) -> QLabel:
        label = QLabel(text)
        label.setObjectName("FieldLabel")
        return label

    def _build_patient_box(self) -> Card:
        box = Card("Patient Details")
        grid = QGridLayout()

        self.f_name = QLineEdit()
        self.f_name.setValidator(V.validator(V.NAME_PATTERN, self))
        self.f_name.setMaxLength(60)
        self.f_name.setPlaceholderText("Letters only")

        self.f_age = QLineEdit()
        self.f_age.setValidator(V.validator(V.DIGITS_PATTERN, self))
        self.f_age.setPlaceholderText("00")
        self.f_age.setAlignment(Qt.AlignCenter)
        self.f_age.setFixedWidth(60)
        self.f_age_unit = T.style_combo(QComboBox())
        for code, word in AGE_UNITS:
            self.f_age_unit.addItem(word, code)
        self.f_age_unit.setToolTip(
            "The unit the age is counted in. Use Months or Days for infants.")
        self.f_age_unit.setMinimumWidth(104)
        self.f_age_unit.currentIndexChanged.connect(self._mark_age)
        self.f_age.textChanged.connect(self._mark_age)
        self.f_sex = T.style_combo(QComboBox())
        self.f_sex.addItems(["M", "F", "Other"])
        self.f_sex.currentTextChanged.connect(self._sex_changed)
        self.f_pid = QLineEdit()
        self.f_pid.setReadOnly(True)
        self.f_pid.setToolTip("Automatically generated unique patient key.")
        self.f_pid.setFixedWidth(130)
        self.f_phone = QLineEdit()
        self.f_phone.setValidator(V.validator(V.PHONE_PATTERN, self))
        self.f_phone.setMaxLength(V.MAX_PHONE)
        self.f_phone.setPlaceholderText("+91 9845012345")
        self.f_phone.setFixedWidth(190)
        self.f_ref = QLineEdit()
        self.f_ref.setValidator(V.validator(V.DOCTOR_PATTERN, self))
        self.f_ref.setMaxLength(60)
        self.f_ref.setPlaceholderText("Referring doctor (optional)")
        self.f_sample = T.style_combo(QComboBox())
        self.f_sample.setEditable(True)
        self.f_sample.lineEdit().setValidator(V.validator(V.SAMPLE_PATTERN, self))
        self.f_sample.lineEdit().setMaxLength(30)
        self.f_sample.addItems(["Blood", "Serum", "Plasma", "EDTA Whole Blood", "Urine"])
        # Real pickers, not text boxes. A free-text date lets "asdf" print as
        # the date on a medical report, and no amount of validation afterwards
        # is as reliable as making the invalid state unreachable.
        self.f_collected = self._date_field()
        self.f_reported = self._date_field()
        self.f_remarks = QLineEdit()
        self.f_remarks.setMaxLength(V.MAX_REMARKS)
        self.l_report_no = QLabel("-")
        self.l_report_no.setObjectName("KeyValue")

        age_row = QWidget()
        age_row.setObjectName("Bare")
        ah = QHBoxLayout(age_row)
        ah.setContentsMargins(0, 0, 0, 0)
        ah.addWidget(self.f_age)
        ah.addWidget(self.f_age_unit)
        ah.addSpacing(S3)
        sex_label = QLabel("Sex:")
        sex_label.setObjectName("FieldLabel")
        ah.addWidget(sex_label)
        ah.addWidget(self.f_sex)
        ah.addStretch(1)

        left = QFormLayout()
        left.setLabelAlignment(Qt.AlignRight | Qt.AlignVCenter)
        left.setHorizontalSpacing(S3)
        left.setVerticalSpacing(6)
        left.addRow(self._label("Patient Name:"), self._described(self.f_name, "name"))
        left.addRow(self._label("Age:"), self._described(age_row, "age"))
        left.addRow(self._label("Patient ID:"),
                    self._described(self.f_pid, "patient_id", "auto-generated"))
        left.addRow(self._label("Phone No:"), self._described(self.f_phone, "phone"))
        right = QFormLayout()
        right.setLabelAlignment(Qt.AlignRight | Qt.AlignVCenter)
        right.setHorizontalSpacing(S3)
        right.setVerticalSpacing(6)
        right.addRow(self._label("Referred By:"), self._described(self.f_ref, "doctor"))
        right.addRow(self._label("Sample Type:"), self._described(self.f_sample, "sample"))
        right.addRow(self._label("Collected On:"),
                     self._described(self.f_collected, "collected"))
        right.addRow(self._label("Reported On:"),
                     self._described(self.f_reported, "reported"))

        grid.setHorizontalSpacing(34)
        grid.addLayout(left, 0, 0)
        grid.addLayout(right, 0, 1)

        remarks_row = QWidget()
        remarks_row.setObjectName("Bare")
        rr = QHBoxLayout(remarks_row)
        rr.setContentsMargins(0, 2, 0, 0)
        rr.addWidget(self._label("Remarks:"))
        rr.addWidget(self._described(self.f_remarks, "remarks"), 1)
        grid.addWidget(remarks_row, 1, 0, 1, 2)

        grid.setColumnStretch(0, 1)
        grid.setColumnStretch(1, 1)
        box.add(grid)
        box.add_header_widget(self._report_no_badge())
        return box

    def _report_no_badge(self) -> QWidget:
        holder = QWidget()
        holder.setObjectName("Bare")
        row = QHBoxLayout(holder)
        row.setContentsMargins(0, 0, 0, 0)
        row.setSpacing(S2)
        caption = QLabel("REPORT NO")
        caption.setObjectName("CardTitle")
        row.addWidget(caption)
        row.addWidget(self.l_report_no)
        return holder

    def _build_panel_box(self) -> Card:
        box = Card("Test Panels", "tick a panel to load its tests")
        self.panel_grid = QGridLayout()
        self.panel_grid.setHorizontalSpacing(S2 + 2)
        self.panel_grid.setVerticalSpacing(6)
        self.panel_boxes = {}
        self.panel_chips = {}
        box.add(self.panel_grid)
        self._fill_panel_chips()
        return box

    def _fill_panel_chips(self):
        """Rebuild the chip row from the saved templates, so a panel created or
        renamed in the Test Templates page shows up here without a restart."""
        grid = self.panel_grid
        while grid.count():
            item = grid.takeAt(0)
            if item.widget():
                item.widget().deleteLater()
        self.panel_boxes.clear()
        self.panel_chips.clear()

        names = templates.panel_names()
        for i, name in enumerate(names):
            chip = QFrame()
            chip.setObjectName("PanelChip")
            chip.setCursor(Qt.PointingHandCursor)
            inner = QHBoxLayout(chip)
            inner.setContentsMargins(S2 + 2, 0, S3, 0)

            cb = QCheckBox(name.split("(")[0].strip())
            cb.setToolTip(f"{name} - tick to load its tests, untick to remove them")
            cb.toggled.connect(lambda checked, n=name: self._panel_toggled(n, checked))
            cb.toggled.connect(lambda checked, n=name: self._style_chip(n, checked))
            inner.addWidget(cb)
            inner.addStretch(1)

            self.panel_boxes[name] = cb
            self.panel_chips[name] = chip
            grid.addWidget(chip, i // 3, i % 3)

        for col in range(3):
            grid.setColumnStretch(col, 1)

    def refresh_panels(self):
        """Called when the templates change. Panels still loaded in the grid are
        left alone - the operator's typed results must survive an edit."""
        checked = {name for name, cb in self.panel_boxes.items() if cb.isChecked()}
        self._fill_panel_chips()
        for name in checked:
            cb = self.panel_boxes.get(name)
            if cb is not None:
                cb.blockSignals(True)
                cb.setChecked(True)
                cb.blockSignals(False)
                self._style_chip(name, True)

    def _style_chip(self, panel: str, checked: bool):
        """Light the whole chip, not just the tick, so a selected panel reads
        at a glance from across the room."""
        chip = self.panel_chips.get(panel)
        if chip is None:
            return
        chip.setObjectName("PanelChipOn" if checked else "PanelChip")
        chip.style().unpolish(chip)
        chip.style().polish(chip)

    def _build_table_box(self) -> Card:
        box = Card("Results", "out-of-range values are flagged H / L automatically",
                   elevated=False)

        self.table = QTableWidget(0, len(COLS))
        self.table.setObjectName("GridTable")
        self.table.setHorizontalHeaderLabels(COLS)
        # Ruled like a worksheet: the operator types a value into one cell and
        # reads it back against a range three columns away, which needs a line
        # to follow rather than a tint.
        self.table.setShowGrid(True)
        self.table.verticalHeader().setDefaultSectionSize(30)
        self.table.setSelectionBehavior(QAbstractItemView.SelectItems)
        self.table.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.table.setAlternatingRowColors(True)
        header = self.table.horizontalHeader()
        header.setSectionResizeMode(0, QHeaderView.Stretch)
        for i in (1, 2, 3):
            header.setSectionResizeMode(i, QHeaderView.Interactive)
        self.table.setColumnWidth(1, 150)
        self.table.setColumnWidth(2, 130)
        self.table.setColumnWidth(3, 190)
        self.table.verticalHeader().setVisible(False)
        self.table.setMinimumHeight(230)
        self.table.itemChanged.connect(self._item_changed)
        box.add(self.table, 1)

        buttons = QHBoxLayout()
        buttons.setSpacing(S2)
        self.add_row_button = icon_button("plus", "Add Row",
                                          "Add a test that is not in a panel")
        self.add_row_button.clicked.connect(self._add_blank_row)
        self.delete_row_button = icon_button("minus", "Delete Row",
                                             "Remove the selected row")
        self.delete_row_button.clicked.connect(self._delete_row)
        buttons.addWidget(self.add_row_button)
        buttons.addWidget(self.delete_row_button)
        buttons.addStretch(1)
        self.row_count_label = QLabel("")
        self.row_count_label.setObjectName("Hint")
        buttons.addWidget(self.row_count_label)
        box.add(buttons)
        return box

    # ----------------------------------------------------------------- billing
    @staticmethod
    def _bill_date_field() -> QDateTimeEdit:
        """Down to the second, because that is what the bill prints and because
        two bills for one patient on one morning have to be tellable apart."""
        field = QDateTimeEdit()
        field.setDisplayFormat("dd-MM-yyyy  hh:mm:ss AP")
        field.setCalendarPopup(True)
        field.setDateTime(QDateTime.currentDateTime())
        field.setMinimumDate(QDate(1900, 1, 1))
        field.setMaximumDateTime(QDateTime.currentDateTime().addYears(1))
        field.setFixedWidth(215)
        return field

    def _amount_field(self, width: int = 130) -> QLineEdit:
        field = QLineEdit()
        field.setObjectName("AmountField")
        field.setValidator(V.validator(V.AMOUNT_PATTERN, self))
        field.setPlaceholderText("0.00")
        field.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        field.setFixedWidth(width)
        # Money is read, checked and re-read at the counter, so it is set larger
        # than body text and given a box of its own height to sit in.
        field.setMinimumHeight(34)
        field.setToolTip("What the patient has paid against this bill. "
                         "Leave blank if nothing has been paid yet.")
        return field

    def _build_bill_box(self) -> Card:
        box = Card("Billing Details",
                   "one line per selected panel - totals update as you type",
                   elevated=False)

        self.f_bill_no = QLineEdit()
        self.f_bill_no.setValidator(V.validator(V.BILL_NO_PATTERN, self))
        self.f_bill_no.setMaxLength(V.MAX_BILL_NO)
        self.f_bill_no.setFixedWidth(150)
        self.f_bill_date = self._bill_date_field()
        self.f_bill_type = T.style_combo(QComboBox())
        self.f_bill_type.addItems(billing.BILL_TYPES)
        self.f_bill_type.setMinimumWidth(170)
        self.f_billed_by = QLineEdit()
        self.f_billed_by.setValidator(V.validator(V.DOCTOR_PATTERN, self))
        self.f_billed_by.setMaxLength(40)
        self.f_billed_by.setPlaceholderText("Name on the bill")
        self.f_billed_by.setFixedWidth(215)

        # Two form columns, the same shape as the patient card, so the labels
        # line up against their fields the way they do everywhere else.
        columns = (
            (("Bill No:", self.f_bill_no, "bill_no"),
             ("Bill Date:", self.f_bill_date, "bill_date")),
            (("Bill Type:", self.f_bill_type, "bill_type"),
             ("Billed By:", self.f_billed_by, "billed_by")),
        )
        head = QHBoxLayout()
        head.setSpacing(34)
        for column in columns:
            form = QFormLayout()
            form.setLabelAlignment(Qt.AlignRight | Qt.AlignVCenter)
            form.setHorizontalSpacing(S3)
            form.setVerticalSpacing(6)
            for label, widget, help_key in column:
                form.addRow(self._label(label), self._described(widget, help_key))
            head.addLayout(form)
        head.addStretch(1)
        box.add(head)

        self.bill_table = QTableWidget(0, len(BILL_COLS))
        self.bill_table.setObjectName("GridTable")
        self.bill_table.setHorizontalHeaderLabels(BILL_COLS)
        self.bill_table.setShowGrid(True)
        self.bill_table.verticalHeader().setVisible(False)
        self.bill_table.verticalHeader().setDefaultSectionSize(34)
        self.bill_table.setSelectionBehavior(QAbstractItemView.SelectItems)
        self.bill_table.setAlternatingRowColors(True)
        bill_header = self.bill_table.horizontalHeader()
        bill_header.setSectionResizeMode(0, QHeaderView.Stretch)
        bill_header.setSectionResizeMode(1, QHeaderView.Fixed)
        self.bill_table.setColumnWidth(1, 170)
        # The amount column is the only thing on this card the operator types,
        # so it is drawn as a box with a 0.00 in it rather than as a bare cell.
        self.bill_table.setItemDelegateForColumn(
            1, AmountDelegate(self.bill_table, V.AMOUNT_PATTERN))
        # One click into the box starts typing: an amount is a two-second edit
        # and a double-click requirement is felt on every single bill.
        self.bill_table.setEditTriggers(self.BILL_TRIGGERS)
        self.bill_table.itemChanged.connect(self._bill_item_changed)
        box.add(self.bill_table)

        self.bill_empty = QLabel(
            "Tick a panel above and its charge appears here.")
        self.bill_empty.setObjectName("Hint")
        box.add(self.bill_empty)

        strip = QHBoxLayout()
        strip.addStretch(1)
        strip.addWidget(self._build_bill_totals())
        box.add(strip)
        # The bill is its own document, so its actions live on its own card
        # rather than lengthening the report's action bar at the foot of the
        # page - four buttons down there already carry the report.
        box.add_header_widget(self._build_bill_actions())
        return box

    def _build_bill_actions(self) -> QWidget:
        holder = QWidget()
        holder.setObjectName("Bare")
        row = QHBoxLayout(holder)
        row.setContentsMargins(0, 0, 0, 0)
        row.setSpacing(S2)
        self.bill_buttons = []
        for icon_name, text, tip, slot in (
            ("preview", "Preview Bill", "See the bill before printing",
             self.preview_bill),
            ("pdf", "Bill PDF", "Save the bill as a PDF file", self.export_bill_pdf),
            ("printer", "Print Bill", "Save the report, then print the bill",
             self.print_bill),
        ):
            button = icon_button(icon_name, text, tip)
            button.clicked.connect(slot)
            row.addWidget(button)
            self.bill_buttons.append(button)
        return holder

    def _build_bill_totals(self) -> QFrame:
        """Total / payable / deposit / balance, stacked under the amount column.

        The deposit is the only editable line, so it sits in the same column as
        the figures it is subtracted from rather than off in a form of its own.
        """
        frame = QFrame()
        frame.setObjectName("BillTotals")
        grid = QGridLayout(frame)
        grid.setContentsMargins(S3, S2 + 2, S3, S2 + 2)
        grid.setHorizontalSpacing(S3)
        grid.setVerticalSpacing(6)

        def caption(text: str, row: int, name: str = "BillLabel"):
            label = QLabel(text)
            label.setObjectName(name)
            label.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
            grid.addWidget(label, row, 0)

        def figure(row: int, name: str = "BillValue") -> QLabel:
            label = QLabel(billing.format_amount(0))
            label.setObjectName(name)
            label.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
            label.setMinimumWidth(130)
            grid.addWidget(label, row, 1)
            return label

        caption("Total Billed", 0)
        self.l_total = figure(0)
        caption("Net Payable", 1)
        self.l_payable = figure(1)

        caption("Net Deposit", 2)
        self.f_deposit = self._amount_field()
        self.f_deposit.textChanged.connect(self._update_bill_totals)
        # The sign sits outside the box: inside it, the operator has to type
        # around it, and the amount validator would reject it anyway.
        deposit_row = QWidget()
        deposit_row.setObjectName("Bare")
        deposit_line = QHBoxLayout(deposit_row)
        deposit_line.setContentsMargins(0, 0, 0, 0)
        deposit_line.setSpacing(S2 - 2)
        deposit_line.addStretch(1)
        rupee = QLabel(billing.CURRENCY)
        rupee.setObjectName("AmountSign")
        deposit_line.addWidget(rupee)
        deposit_line.addWidget(self.f_deposit)
        grid.addWidget(deposit_row, 2, 1)

        # The description belongs directly under the field it describes, the way
        # every other field on the page carries its one line of plain English.
        deposit_help = QLabel(FIELD_HELP["deposit"])
        deposit_help.setObjectName("FieldHelp")
        deposit_help.setWordWrap(True)
        deposit_help.setMaximumWidth(290)
        deposit_help.setAlignment(Qt.AlignRight | Qt.AlignTop)
        grid.addWidget(deposit_help, 3, 0, 1, 2)

        grid.addWidget(hrule(), 4, 0, 1, 2)

        caption("BALANCE", 5, "BillLabelStrong")
        self.l_balance = figure(5, "BillBalance")
        return frame

    def _fill_bill_table(self, items):
        self._bill_loading = True
        try:
            self.bill_table.setRowCount(0)
            for i, item in enumerate(items):
                self.bill_table.insertRow(i)
                service = QTableWidgetItem(item.service)
                # The service name is not typed here - it is whatever panel the
                # operator ticked, and editing it would only let the bill drift
                # away from the results it is charging for.
                service.setFlags(Qt.ItemIsEnabled | Qt.ItemIsSelectable)
                service.setToolTip("Comes from the panels selected above.")
                self.bill_table.setItem(i, 0, service)
                amount = QTableWidgetItem(item.amount)
                amount.setTextAlignment(Qt.AlignRight | Qt.AlignVCenter)
                self.bill_table.setItem(i, 1, amount)
        finally:
            self._bill_loading = False
        self.bill_empty.setVisible(not items)
        self.bill_table.setVisible(bool(items))
        # A bill has a handful of lines, so the table is sized to its contents
        # rather than left as a fixed box with an empty half. Past the cap it
        # scrolls, which only happens on a report carrying a dozen panels.
        rows = self.bill_table.horizontalHeader().height() + 2
        rows += sum(self.bill_table.rowHeight(r) for r in range(len(items)))
        self.bill_table.setFixedHeight(min(rows, 240))

    def _sync_bill_items(self):
        """Re-derive the bill lines from the results grid, keeping typed amounts.

        Called whenever the selected work changes - a panel ticked or unticked, a
        row added, deleted or renamed - so the bill can never be charging for a
        panel that is no longer on the report.
        """
        items = billing.sync_items(self._collect_billing(), self._collect_rows())
        self._fill_bill_table(items)
        self._update_bill_totals()

    def _bill_item_changed(self, item):
        if not self._bill_loading:
            self._update_bill_totals()

    def _mark_amount_cell(self, row: int) -> bool:
        """Red-italic an unusable amount, the same way the results grid marks a
        bad cell. Returns True when the cell is fine."""
        cell = self.bill_table.item(row, 1)
        if cell is None:
            return True
        problem = V.check_amount(cell.text(), "amount")
        font = QFont()
        font.setBold(bool(problem))
        font.setItalic(bool(problem))
        cell.setFont(font)
        cell.setForeground(QBrush(QColor(DANGER if problem else "#000000")))
        cell.setToolTip(problem or "")
        return not problem

    def _update_bill_totals(self):
        """Recompute and repaint the four figures. Invalid amounts count as
        nothing rather than freezing the total, so the number on screen always
        matches the amounts that are actually usable."""
        if self._bill_loading:
            return
        self._bill_loading = True
        try:
            for row in range(self.bill_table.rowCount()):
                self._mark_amount_cell(row)
        finally:
            self._bill_loading = False

        figures = billing.summary(self._collect_billing())
        self.l_total.setText(billing.format_amount(figures["total_billed"]))
        self.l_payable.setText(billing.format_amount(figures["net_payable"]))
        self.l_balance.setText(billing.format_amount(figures["balance"]))
        # Amber-free: owed is crimson, settled is green. Same repolish dance as
        # the panel chips, because an object name change alone does not restyle.
        due = figures["balance"] > 0
        self.l_balance.setObjectName("BillBalance" if due else "BillBalanceClear")
        self.l_balance.style().unpolish(self.l_balance)
        self.l_balance.style().polish(self.l_balance)

    def _load_billing(self, bill: Billing):
        """Put a stored bill back on the form.

        The first build stored the day alone, so that format is tried too; a date
        the app still cannot read falls back to now rather than throwing."""
        self.f_bill_no.setText(bill.bill_no or storage.peek_bill_no())
        when = QDateTime.fromString(bill.bill_date or "", billing.BILL_QT_DATE_FMT)
        if not when.isValid():
            legacy = QDate.fromString(bill.bill_date or "", "dd-MM-yyyy")
            when = legacy.startOfDay() if legacy.isValid() else QDateTime()
        self.f_bill_date.setDateTime(
            when if when.isValid() else QDateTime.currentDateTime())
        self.f_bill_type.setCurrentText(bill.bill_type or billing.DEFAULT_BILL_TYPE)
        self.f_billed_by.setText(bill.billed_by or storage.load_profile().billed_by)
        self.f_deposit.setText(bill.net_deposit)
        self._fill_bill_table(bill.items)
        self._update_bill_totals()

    def _collect_billing(self) -> Billing:
        items = []
        for row in range(self.bill_table.rowCount()):
            service = self.bill_table.item(row, 0)
            amount = self.bill_table.item(row, 1)
            if service is None or not service.text().strip():
                continue
            items.append(BillItem(
                service=service.text().strip(),
                amount=(amount.text().strip() if amount else ""),
            ))
        return Billing(
            bill_no=self.f_bill_no.text().strip(),
            bill_date=self.f_bill_date.dateTime().toString(billing.BILL_QT_DATE_FMT),
            bill_type=self.f_bill_type.currentText(),
            billed_by=self.f_billed_by.text().strip(),
            net_deposit=self.f_deposit.text().strip(),
            items=items,
        )

    # -------------------------------------------------------- bill as a document
    def _bill_html(self) -> str:
        return build_bill(self.collect(), storage.load_profile())

    def _bill_ready(self) -> bool:
        """A bill with no figures on it is not a bill. Checked before every bill
        action so the operator is told why, instead of being handed a blank."""
        if not self._validate():
            return False
        if not billing.has_content(self._collect_billing()):
            self.notify.emit(
                "Enter an amount against at least one service before printing "
                "the bill.", "warning")
            return False
        return True

    def preview_bill(self):
        if self._bill_ready():
            printing.preview_report(self._bill_html(), self, "Bill Preview",
                                    printing.BILL_PAGE)

    def print_bill(self):
        """Save before printing, for the same reason the report does: a bill
        handed to a patient must exist in the history, with its number."""
        if not self._bill_ready():
            return
        if not self.read_only and not self.save():
            return
        if printing.print_report(self._bill_html(), self, "Print Bill",
                                printing.BILL_PAGE):
            self.notify.emit(
                f"Bill {self.f_bill_no.text()} sent to the printer.", "success")
        else:
            self.notify.emit("Printing cancelled.", "warning")

    def export_bill_pdf(self):
        if not self._bill_ready():
            return
        default = safe_filename(
            f"Bill_{self.f_bill_no.text()}_{self.f_name.text().strip()}") + ".pdf"
        path, _ = QFileDialog.getSaveFileName(self, "Export Bill PDF", default,
                                              "PDF (*.pdf)")
        if path:
            printing.export_pdf(self._bill_html(), path, printing.BILL_PAGE)
            QMessageBox.information(self, "Exported", f"Saved to:\n{path}")

    def _build_actions(self) -> QHBoxLayout:
        row = QHBoxLayout()
        row.setSpacing(S2)
        self.edit_buttons = [self.add_row_button, self.delete_row_button]
        clear = icon_button("clear", "Clear", "Start a blank report")
        clear.clicked.connect(self.clear_clicked)
        row.addWidget(clear)
        row.addStretch(1)

        for icon_name, text, tip, slot in (
            ("save", "Save", "Save without printing", self.save),
            ("preview", "Print Preview", "See the report before printing", self.preview),
            ("pdf", "Export PDF", "Save the report as a PDF file", self.export_pdf),
        ):
            btn = icon_button(icon_name, text, tip)
            btn.clicked.connect(slot)
            row.addWidget(btn)
            if text == "Save":
                self.edit_buttons.append(btn)

        self.print_button = icon_button(
            "printer", "Save and Print", "Save, then open the printer", "Primary")
        self.print_button.setIcon(icons.icon("printer", "#ffffff", 17))
        self.print_button.setMinimumWidth(178)
        self.print_button.clicked.connect(self.print_report)
        row.addWidget(self.print_button)
        return row

    # --------------------------------------------------------------- age unit
    def age_unit_code(self) -> str:
        """The stored code ("Y"/"M"/"D") behind the word the operator sees."""
        return self.f_age_unit.currentData() or "Y"

    def set_age_unit(self, code: str):
        index = self.f_age_unit.findData((code or "Y").upper()[:1])
        self.f_age_unit.setCurrentIndex(max(0, index))

    # ------------------------------------------------------------ read-only
    def set_read_only(self, locked: bool, message: str = ""):
        """A saved report opens locked: it is a medical record that has already
        been printed and handed over, so changing it should be deliberate."""
        self.read_only = locked
        self.lock_bar.setVisible(locked)
        if message:
            self.lock_message.setText(message)
        self.header.title.setText("Saved Report" if locked else "New Report")
        self.print_button.setText("Print" if locked else "Save and Print")

        for widget in (self.f_name, self.f_age, self.f_phone, self.f_ref,
                       self.f_remarks, self.f_bill_no, self.f_billed_by,
                       self.f_deposit):
            widget.setReadOnly(locked)
        for widget in (self.f_collected, self.f_reported, self.f_bill_date):
            widget.setReadOnly(locked)
            widget.setCalendarPopup(not locked)
        for widget in (self.f_age_unit, self.f_sex, self.f_sample,
                       self.f_bill_type):
            widget.setEnabled(not locked)
        for cb in self.panel_boxes.values():
            cb.setEnabled(not locked)

        triggers = (QAbstractItemView.NoEditTriggers if locked
                    else QAbstractItemView.DoubleClicked
                    | QAbstractItemView.EditKeyPressed
                    | QAbstractItemView.AnyKeyPressed)
        self.table.setEditTriggers(triggers)
        # The bill keeps its single-click editing: an amount box that needs a
        # double-click reads as read-only, which is the confusion this fixes.
        self.bill_table.setEditTriggers(
            QAbstractItemView.NoEditTriggers if locked else self.BILL_TRIGGERS)
        for button in self.edit_buttons:
            button.setEnabled(not locked)

    def request_edit_access(self) -> bool:
        """Ask for the password and unlock the form if it is correct."""
        from .password_dialog import request_unlock

        if not self.read_only:
            return True
        if request_unlock(self, "edit this saved report"):
            self.set_read_only(False)
            self.notify.emit(
                "Report unlocked - saving now overwrites the stored record.",
                "warning")
            return True
        self.notify.emit("Report stays read-only.", "info")
        return False

    # ----------------------------------------------------------- form state
    def is_dirty(self) -> bool:
        """True if the form holds anything the operator typed.

        The patient ID and the timestamps are generated, so they never count as
        user input - otherwise a freshly cleared form would look dirty."""
        typed = (self.f_name, self.f_age, self.f_phone, self.f_ref,
                 self.f_remarks, self.f_deposit)
        return any(w.text().strip() for w in typed) or self.table.rowCount() > 0

    def clear_clicked(self):
        """Clear is destructive to unsaved typing, so confirm before wiping it."""
        if self.is_dirty():
            confirm = QMessageBox.question(
                self, "Clear form",
                "Clear the form and start a new report?\n\n"
                "Anything not saved yet will be lost.",
                QMessageBox.Yes | QMessageBox.No, QMessageBox.No,
            )
            if confirm != QMessageBox.Yes:
                return
        self.new_report()
        self.notify.emit("Form cleared - ready for a new report.", "info")

    # ------------------------------------------------------------ table logic
    def _append_row(self, row: TestRow):
        self._loading = True
        r = self.table.rowCount()
        self.table.insertRow(r)
        for col, value in enumerate((row.name, row.result, row.unit, row.ref)):
            item = QTableWidgetItem(value)
            if col == 0:
                item.setData(Qt.UserRole, row.panel)
                item.setData(HEADING_ROLE, row.kind)
            self.table.setItem(r, col, item)

        if row.is_heading():
            self._style_heading(r)
        self._loading = False
        self._restyle_row(r)
        self._update_row_count()

    def _style_heading(self, r: int):
        """A sub-heading is a band across the grid: no result, unit or range."""
        head = self.table.item(r, 0)
        font = QFont()
        font.setBold(True)
        head.setFont(font)
        head.setForeground(QBrush(QColor(ACCENT_DARK)))
        head.setBackground(QBrush(QColor(SURFACE_ALT)))
        for col in (1, 2, 3):
            cell = self.table.item(r, col)
            cell.setText("")
            cell.setFlags(Qt.ItemIsEnabled)
            cell.setBackground(QBrush(QColor(SURFACE_ALT)))

    def is_heading_row(self, r: int) -> bool:
        item = self.table.item(r, 0)
        return item is not None and item.data(HEADING_ROLE) == "heading"

    def _update_row_count(self):
        n = sum(1 for r in range(self.table.rowCount()) if not self.is_heading_row(r))
        self.row_count_label.setText(f"{n} test{'s' if n != 1 else ''}" if n else "")

    def _delete_row(self):
        rows = sorted({i.row() for i in self.table.selectedIndexes()}, reverse=True)
        if not rows:
            self.notify.emit("Select a cell in the row you want to delete.", "warning")
            return
        for r in rows:
            self.table.removeRow(r)
        self._update_row_count()
        self._sync_bill_items()

    def _add_blank_row(self):
        self._append_row(TestRow("Investigations", "", "", "", ""))
        self._sync_bill_items()

    def _item_changed(self, item):
        if self._loading or self._styling:
            return
        self._restyle_row(item.row())
        if item.column() == 0:
            # Naming a hand-added row is what makes it billable, so the bill has
            # to follow the test name as well as the panel ticks.
            self._sync_bill_items()

    def _cell_problem(self, r: int, col: int):
        """The validation message for one grid cell, or None."""
        item = self.table.item(r, col)
        text = item.text() if item else ""
        if col == 0:
            return V.check_test_name(text, "test name")
        if col == 1:
            return V.check_result_value(text)
        if col == 2:
            return V.check_unit(text)
        if col == 3:
            return V.check_reference(text)
        return None

    def _mark_cell(self, r: int, col: int):
        """Mark an invalid cell in red.

        Not a background tint: a Qt stylesheet on QTableWidget::item takes over
        item rendering and ignores the model's background brush, so the tint is
        simply never drawn. Foreground colour still gets through."""
        item = self.table.item(r, col)
        if item is None:
            return
        problem = self._cell_problem(r, col)
        if not problem and col == 1:
            # The result column already carries its H / L styling; resetting it
            # here would wipe the red on an out-of-range value.
            return None

        font = QFont()
        font.setBold(bool(problem))
        font.setItalic(bool(problem))
        item.setFont(font)
        item.setForeground(QBrush(QColor(DANGER if problem else "#000000")))
        item.setToolTip(problem or "")
        return problem

    def _restyle_row(self, r: int):
        """Re-entrant by nature: setting a font or colour on an item emits
        itemChanged, which lands back here. The guard stops the H/L styling and
        the invalid-cell marking from overwriting each other forever."""
        if self.is_heading_row(r) or self._styling:
            return
        self._styling = True
        try:
            self._restyle_row_now(r)
        finally:
            self._styling = False

    def _restyle_row_now(self, r: int):
        result_item = self.table.item(r, 1)
        ref_item = self.table.item(r, 3)
        if result_item is None or ref_item is None:
            return

        flag = flag_for(result_item.text(), ref_item.text())
        font = QFont()
        font.setBold(bool(flag))
        result_item.setFont(font)
        result_item.setForeground(QBrush(QColor("#c00000" if flag else "#000000")))
        result_item.setToolTip({"H": "Above reference range",
                                "L": "Below reference range"}.get(flag, ""))

        # last, so an invalid cell always shows as invalid rather than as a flag
        for col in (0, 1, 2, 3):
            self._mark_cell(r, col)

    def _panel_toggled(self, panel: str, checked: bool):
        if checked:
            for row in templates.rows_for(panel):
                self._append_row(TestRow(
                    panel=panel, name=row["name"], result="", unit=row.get("unit", ""),
                    ref=templates.ref_for(row, self.f_sex.currentText()),
                    kind=row.get("kind", "test")))
        else:
            for r in range(self.table.rowCount() - 1, -1, -1):
                item = self.table.item(r, 0)
                if item is not None and item.data(Qt.UserRole) == panel:
                    self.table.removeRow(r)
            self._update_row_count()
        self._sync_bill_items()

    def _sex_changed(self):
        """Re-resolve sex-specific reference ranges when the patient's sex changes."""
        sex = self.f_sex.currentText()
        self._loading = True
        for r in range(self.table.rowCount()):
            name_item = self.table.item(r, 0)
            if name_item is None:
                continue
            panel = name_item.data(Qt.UserRole)
            for row in templates.rows_for(panel or ""):
                if row["name"] == name_item.text() and row.get("kind") != "heading":
                    self.table.item(r, 3).setText(templates.ref_for(row, sex))
                    break
        self._loading = False
        for r in range(self.table.rowCount()):
            self._restyle_row(r)

    # --------------------------------------------------------------- report io
    def _collect_rows(self):
        """The result rows as they stand in the grid. Shared by `collect` and by
        the billing sync, so the bill is always derived from exactly the rows
        that will be saved and printed."""
        rows = []
        for r in range(self.table.rowCount()):
            name = self.table.item(r, 0)
            if name is None or not name.text().strip():
                continue
            heading = self.is_heading_row(r)
            rows.append(TestRow(
                panel=name.data(Qt.UserRole) or "Investigations",
                name=name.text().strip(),
                result="" if heading else
                (self.table.item(r, 1).text() if self.table.item(r, 1) else "").strip(),
                unit="" if heading else
                (self.table.item(r, 2).text() if self.table.item(r, 2) else "").strip(),
                ref="" if heading else
                (self.table.item(r, 3).text() if self.table.item(r, 3) else "").strip(),
                kind="heading" if heading else "test",
            ))
        return rows

    def collect(self) -> Report:
        return Report(
            id=self.current_id,
            report_no=self.current_report_no,
            patient_name=self.f_name.text().strip(),
            age=self.f_age.text().strip(),
            age_unit=self.age_unit_code(),
            sex=self.f_sex.currentText(),
            patient_id=self.f_pid.text().strip(),
            phone=V.normalise_phone(self.f_phone.text()),
            referred_by=self.f_ref.text().strip(),
            sample_type=self.f_sample.currentText().strip(),
            collected_on=self.f_collected.dateTime().toString(QT_DATE_FMT),
            reported_on=self.f_reported.dateTime().toString(QT_DATE_FMT),
            remarks=self.f_remarks.text().strip(),
            panels=[n for n, cb in self.panel_boxes.items() if cb.isChecked()],
            rows=self._collect_rows(),
            billing=self._collect_billing(),
            created_at=self.current_created_at,
        )

    def new_report(self):
        self._loading = True
        self.current_id = ""
        self.current_report_no = ""
        self.current_created_at = ""
        for name, cb in self.panel_boxes.items():
            cb.blockSignals(True)
            cb.setChecked(False)
            cb.blockSignals(False)
            self._style_chip(name, False)
        self.table.setRowCount(0)
        self._update_row_count()
        for field in (self.f_name, self.f_age, self.f_phone, self.f_ref,
                      self.f_remarks):
            field.clear()
        self.f_pid.setText(storage.peek_patient_id())
        self.f_sex.setCurrentIndex(0)
        self.f_age_unit.setCurrentIndex(0)
        self.f_sample.setCurrentIndex(0)
        now = QDateTime.currentDateTime()
        self.f_collected.setDateTime(now)
        self.f_reported.setDateTime(now)
        self.l_report_no.setText(storage.peek_report_no())
        self.f_bill_no.setText(storage.peek_bill_no())
        self.f_bill_date.setDateTime(QDateTime.currentDateTime())
        self.f_bill_type.setCurrentIndex(0)
        # Typed once on the Laboratory Profile, not once per bill.
        self.f_billed_by.setText(storage.load_profile().billed_by)
        self.f_deposit.clear()
        self._fill_bill_table([])
        self._update_bill_totals()
        self.set_read_only(False)
        self._loading = False
        self.f_name.setFocus()

    def forget_if_deleted(self, deleted_ids) -> bool:
        """If the report currently open in the form was deleted from History,
        the form must not keep showing it - saving again would resurrect it."""
        if self.current_id and self.current_id in set(deleted_ids):
            self.new_report()
            return True
        return False

    def load_report(self, report: Report, as_copy: bool = False):
        self.new_report()
        self._loading = True
        if not as_copy:
            self.current_id = report.id
            self.current_report_no = report.report_no
            self.current_created_at = report.created_at
            self.l_report_no.setText(report.report_no)
        self.f_name.setText(report.patient_name)
        self.f_age.setText(report.age)
        self.set_age_unit(report.age_unit or "Y")
        self.f_sex.blockSignals(True)
        self.f_sex.setCurrentText(report.sex or "M")
        self.f_sex.blockSignals(False)
        self.f_pid.setText(report.patient_id or storage.peek_patient_id())
        self.f_phone.setText(report.phone)
        self.f_ref.setText(report.referred_by)
        self.f_sample.setCurrentText(report.sample_type)
        if not as_copy:
            self._set_date(self.f_collected, report.collected_on)
            self._set_date(self.f_reported, report.reported_on)
            self.f_remarks.setText(report.remarks)
            # A duplicate is a fresh visit: it keeps the patient and the panels
            # but not the previous bill, so its own number, date and amounts are
            # left to be filled in - the same reason its results start blank.
            self._load_billing(report.billing)
        for name, cb in self.panel_boxes.items():
            cb.blockSignals(True)
            cb.setChecked(name in report.panels)
            cb.blockSignals(False)
            self._style_chip(name, name in report.panels)
        self.table.setRowCount(0)
        self._loading = False
        self.set_read_only(
            not as_copy,
            f"Viewing saved report {report.report_no} for {report.patient_name}. "
            "Saved reports open read-only so a finished record is not changed "
            "by accident.")
        for row in report.rows:
            self._append_row(TestRow(row.panel, row.name, "" if as_copy else row.result,
                                     row.unit, row.ref, row.kind))
        # Reconcile once at the end rather than per row: a saved bill already
        # matches its rows, so this is a no-op for a well-formed report and a
        # repair for one that was hand-edited on disk.
        self._sync_bill_items()

    # ----------------------------------------------------------------- actions
    def _mark_age(self):
        """Tint the age box while it holds an implausible value."""
        bad = bool(self.f_age.text().strip()) and bool(
            V.check_age(self.f_age.text(), self.age_unit_code()))
        self.f_age.setStyleSheet(
            "border: 1px solid #c0392b; background: #fdf3f2;" if bad else "")

    def _validate(self) -> bool:
        problem = V.first_error(
            V.check_person_name(self.f_name.text(), "patient name"),
            V.check_age(self.f_age.text(), self.age_unit_code()),
            V.check_optional_name(self.f_ref.text(), "referring doctor's name"),
            V.check_phone(self.f_phone.text(), "patient's phone number"),
        )
        if problem:
            self.notify.emit(problem, "warning")
            if "age" in problem.lower():
                self.f_age.setFocus()
            elif "phone" in problem.lower():
                self.f_phone.setFocus()
            elif "doctor" in problem.lower():
                self.f_ref.setFocus()
            else:
                self.f_name.setFocus()
            return False

        if self.table.rowCount() == 0:
            self.notify.emit("Select at least one panel, or add a test row.", "warning")
            return False

        for r in range(self.table.rowCount()):
            if self.is_heading_row(r):
                if not self.table.item(r, 0).text().strip():
                    self.notify.emit(f"Row {r + 1}: give the sub-heading a name.",
                                     "warning")
                    self.table.setCurrentCell(r, 0)
                    return False
                continue
            for col, field in ((0, "test"), (1, "result"), (2, "unit"),
                               (3, "reference range")):
                message = self._cell_problem(r, col)
                if message:
                    self.notify.emit(f"Row {r + 1} ({field}): {message}", "warning")
                    self.table.setCurrentCell(r, col)
                    return False

        return self._validate_billing()

    def _validate_billing(self) -> bool:
        """Billing is optional, so a blank bill is valid. What is not valid is a
        figure that cannot be added up, or a deposit larger than the bill it is
        being paid against - refunds are out of scope, so a negative balance can
        only be a slipped keystroke."""
        problem = V.first_error(
            V.check_bill_no(self.f_bill_no.text()),
            V.check_optional_name(self.f_billed_by.text(), "billed-by name"),
        )
        if problem:
            self.notify.emit(problem, "warning")
            (self.f_billed_by if "billed-by" in problem
             else self.f_bill_no).setFocus()
            return False

        for row in range(self.bill_table.rowCount()):
            service = self.bill_table.item(row, 0)
            amount = self.bill_table.item(row, 1)
            label = f"amount for {service.text()}" if service else "amount"
            message = V.check_amount(amount.text() if amount else "", label)
            if message:
                self.notify.emit(message, "warning")
                self.bill_table.setCurrentCell(row, 1)
                return False

        problem = V.check_amount(self.f_deposit.text(), "net deposit")
        if problem:
            self.notify.emit(problem, "warning")
            self.f_deposit.setFocus()
            return False

        figures = billing.summary(self._collect_billing())
        if figures["balance"] < 0:
            self.notify.emit(
                f"The net deposit ({billing.format_money(figures['net_deposit'])}) "
                f"is more than the net payable amount "
                f"({billing.format_money(figures['net_payable'])}). "
                "Check the amounts before saving.", "warning")
            self.f_deposit.setFocus()
            return False
        return True

    def save(self) -> bool:
        if self.read_only:
            self.notify.emit(
                "This saved report is read-only. Use Unlock to Edit to change it.",
                "warning")
            return False
        if not self._validate():
            return False
        report = storage.save_report(self.collect())
        self.current_id = report.id
        self.current_report_no = report.report_no
        self.current_created_at = report.created_at
        self.l_report_no.setText(report.report_no)
        self.f_pid.setText(report.patient_id)
        self.f_phone.setText(report.phone)
        # storage allocates the bill number and date when they were left blank,
        # so show what was actually stored rather than what was on screen.
        self._load_billing(report.billing)
        self.saved.emit()
        if storage.should_ask_for_backup():
            self._ask_for_drive()
        # One toast, not two: a backup problem must not be painted over by
        # the success message that would otherwise follow it.
        saved = (f"Report {report.report_no} saved for {report.patient_name} "
                 f"({report.patient_id}).")
        problem = self._backup(report)
        if problem:
            self.notify.emit(saved + " " + problem, "warning")
        elif storage.backup_dir():
            self.notify.emit(saved + " Copied to the backup folder.", "success")
        else:
            self.notify.emit(saved, "success")
        return True

    # Swappable so a headless run (tests, scripts) never blocks on the dialog.
    drive_prompt = staticmethod(ask_for_drive)

    def _ask_for_drive(self):
        problem = apply_answer(self.drive_prompt(self))
        if problem:
            self.notify.emit(problem, "warning")

    def _backup(self, report) -> str:
        """Copy the saved report to the backup folder as data plus a PDF.

        The PDF is what the lab actually wants in Drive - something they can
        open on a phone and send to a patient - and it is rendered here rather
        than in storage because only the UI layer can reach the printer stack.
        Returns a one-line problem to show, or "" when all went well (or
        backup is off). Never raises: the report is already safe on disk."""
        if not storage.backup_dir():
            return ""
        month = storage.backup_copy(report)
        if not month:
            return ("The backup folder could not be written - check it in "
                    "Laboratory Profile.")
        pdf = os.path.join(month, storage.backup_name(report) + ".pdf")
        try:
            printing.export_pdf(build(report, storage.load_profile()), pdf)
        except OSError:
            pass
        # QPrinter reports nothing when it cannot write, so look for the file.
        if not os.path.isfile(pdf):
            return "Backed up the data, but the PDF copy could not be written."
        return ""

    def _html(self) -> str:
        return build(self.collect(), storage.load_profile())

    def preview(self):
        if self._validate():
            printing.preview_report(self._html(), self)

    def print_report(self):
        """Save before printing, so nothing leaves the app unrecorded.

        A locked report is already saved, so it prints straight away - printing
        does not change the record, and refusing a reprint would just push the
        operator to History for something they are already looking at."""
        if self.read_only:
            if not self._validate():
                return
            if printing.print_report(self._html(), self):
                self.notify.emit(
                    f"Report {self.current_report_no} sent to the printer.", "success")
            return
        if not self.save():
            return
        if printing.print_report(self._html(), self):
            self.notify.emit(f"Report {self.current_report_no} sent to the printer.", "success")
        else:
            self.notify.emit(
                f"Printing cancelled. Report {self.current_report_no} is saved in History.",
                "warning")

    def export_pdf(self):
        if not self._validate():
            return
        default = f"{self.f_name.text().strip() or 'report'}.pdf".replace(" ", "_")
        path, _ = QFileDialog.getSaveFileName(self, "Export PDF", default, "PDF (*.pdf)")
        if path:
            printing.export_pdf(self._html(), path)
            QMessageBox.information(self, "Exported", f"Saved to:\n{path}")
